import {
    Attribute,
    AutoGeneratedHashKey,
    HashKey,
    RangeKey,
    Table,
    VersionAttribute,
  } from '@skypress/nestjs-dynamodb'
//   import * as nanoid from 'nanoid'
  
  @Table('restaurant')
export class Restaurant {
  @RangeKey()
  id: string

  @HashKey()
  breed: string

  @Attribute()
  age: number

  @Attribute()
  alive?: boolean
  // This property will not be saved to DynamoDB.
//   notPersistedToDynamoDb: string
}
